server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server: 
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    client:
      clientId: 465763836153-ekrf4jqi7894ouqsqau2m6kjkclbvhhb.apps.googleusercontent.com
      clientSecret: 2NwNsIrDD-SwyU-hS6L2iMVV
      redirectUri: http://localhost:3000/login/gmailCallback
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

zuul:
  routes:
    product-category:
      path: /product-category/**
      url: http://localhost:3000/e-commerce/product-category
    product:
      path: /product/**
      url: http://localhost:3000/e-commerce/product